// client/src/lib/components/WindowManager.svelte
<script lang="ts">
  import { Window } from "@encrypted-forest/client";
  import type { WindowState } from "@encrypted-forest/client";

  let {
    windows = [],
  }: {
    windows?: WindowState[];
  } = $props();

  let topZIndex = $state(100);

  function bringToFront(id: string) {
    topZIndex += 1;
    const win = windows.find((w) => w.id === id);
    if (win) {
      win.zIndex = topZIndex;
    }
  }
</script>

{#each windows as win (win.id)}
  <Window
    title={win.title}
    bind:visible={win.visible}
    bind:x={win.x}
    bind:y={win.y}
    bind:width={win.width}
    bind:height={win.height}
    zIndex={win.zIndex}
    onfocus={() => bringToFront(win.id)}
  >
    <p>Window content: {win.id}</p>
  </Window>
{/each}

// solidjs-client/src/components/WindowManager.tsx
/**
 * Manages draggable TUI windows.
 */

import { For, type Accessor } from "solid-js";
import { Window } from "@encrypted-forest/solidjs-sdk";
import type { WindowState } from "@encrypted-forest/solidjs-sdk";

interface WindowManagerProps {
  windows: Accessor<WindowState[]>;
  onClose: (id: string) => void;
  onFocus: (id: string) => void;
  renderContent: (id: string) => any;
}

export default function WindowManager(props: WindowManagerProps) {
  return (
    <For each={props.windows()}>
      {(win) => (
        <Window
          title={win.title}
          visible={win.visible}
          x={win.x}
          y={win.y}
          width={win.width}
          height={win.height}
          zIndex={win.zIndex}
          onclose={() => props.onClose(win.id)}
          onfocus={() => props.onFocus(win.id)}
        >
          {props.renderContent(win.id)}
        </Window>
      )}
    </For>
  );
}
